business:
  name: COLMADO JUAN


#DATA TO EMULATE STATIC BOUGHT
staticpurchase:
  fruits:
    - name: PEAR
      quantity: 80
    - name: ORANGE
      quantity: 10
    - name: APPLE
      quantity: 80

productprices:
  prices:
    - name: PEAR
      price: 5.5
    - name: ORANGE
      price: 3.5
    - name: APPLE
      price: 2

active-offers: 0,1,2,3


#SPRING CONF
spring:
  datasource:
    url: jdbc:h2:file:./db/store;DB_CLOSE_DELAY=-1
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true
    console.settings.web-allow-others: false