business:
  name: COLMADO JUAN


#DATA TO EMULATE STATIC BOUGHT
staticpurchase:
  fruits:
    - name: PEAR
      quantity: 80
    - name: ORANGE
      quantity: 10
    - name: APPLE
      quantity: 80

productprices:
  prices:
    - name: PEAR
      price: 5.5
    - name: ORANGE
      price: 3.5
    - name: APPLE
      price: 2

active-offers: 0,1,2,3


