#SPRING CONF
spring:
  datasource:
    url: jdbc:h2:file:./db/store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false

#BUSINESS CONF
business:
  name: COLMADO JUAN


#STATIC BOUGHT
staticpurchase:
  fruits:
    - name: PEAR
      quantity: 80
    - name: ORANGE
      quantity: 10
    - name: APPLE
      quantity: 80

productprices:
  prices:
    - name: PEAR
      price: 5.5
    - name: ORANGE
      price: 3.5
    - name: APPLE
      price: 2

#OFFERS CONF
active-offers: 0,1,2,3

